# Generated by Django 2.0.7 on 2018-07-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Completed')], default='A', max_length=1)),
            ],
        ),
    ]
